Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: OmniGallery-Themes-${self:provider.stage}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: themeId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: themeId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST